### ISSUE TITLE
Feature request: smart adjustment for bounding box

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1006]
It would be helpful if the bounding box in the same staff line or the entire page can automatically adjust their height based on one bounding box corrected by the user.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes for this new action. Now after you adjust one bbox, neon has a `Match Height` option that can take the y position of the selected bbox, and make all the other bbox on the same staff line align with it. The x-axis is a bit tricky so I haven't made changes for the x axis yet. What I can do is to make assign the x-value of the right border to the left border of the next bbox when there is an overlap. But this can also hinder your correction if one bbox is too wide and the overlap area is too wide. Please let me know what you think.

**Comment by JoyfulGen** [comment]
Weeeeee this is so cool and convenient!!! @yinanazhou I love it :))) One thought: in a situation like the one below, where the staff is significantly tilted, the height matching works for the first half of the staff, but the BBs start getting misaligned with their syllables. Demo:
<img width="864" alt="BBs height adjustment" src="https://github.com/DDMAL/Neon/assets/83373378/4d6b4acc-9a4a-4923-a858-a9efaf2b41e3">
Would it be possible to have the other BBs match the distance to the staff line, rather than the absolute height? And to have that calculation follow the tilt of the staff, if there is one? Then, not only would the height be right, but the position on the page also. Does that make sense?

About this:

>  What I can do is to make assign the x-value of the right border to the left border of the next bbox when there is an overlap. But this can also hinder your correction if one bbox is too wide and the overlap area is too wide. Please let me know what you think.

I agree that this solution could be annoying, because the initial bounding box sizes are really not guaranteed to be correct. However, something like this would be extremely useful once the corrector started correcting. So for example, if the corrector moves the left or right border of a bounding box and the resulting border overlaps another bounding box, then that other bounding box automatically adjusts to remove the overlap. In other words, the automatic removal of overlap only happens if and when the corrector interacts with a bounding box. Then half the adjustments would be made as the corrector went along! What do you think?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I'm glad that you like this feature! I totally agree with you. I will let you know when the change is on.

**Comment by yinanazhou** [comment]
@JoyfulGen, what do you think is a good name for this button? I feel like `Match Height` does not make sense because we are adding x-axis adjustment to it.

**Comment by annamorphism** [comment]
maybe just something like Adjust Size(s)? the one confusing thing I would think is that a new user would probably think you are adjusting the size of that bounding box, not of everything else on the staff...

**Comment by JoyfulGen** [comment]
I actually don't mind `Match Height` because I feel like our brain compensates for the staff tilt by considering the staff line to be straight, even if it's not. Would it be too long to have `Match Height for whole row`? Or something like that?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes. Please let me know what you think.

**Comment by JoyfulGen** [comment]
It works beautifully! Even more satisfying than before, thank you @yinanazhou :) Shall I close the issue, or leave it open for eventual x-value adjustments?

**Comment by yinanazhou** [comment]
I think we can close this issue? I'll soon push the changes about resulting bbox size in ungroup, so there will not be much big overlap as before.

**Comment by JoyfulGen** [comment]
@yinanazhou I'm sorry to be reopening this issue, but I've just realized I misunderstood the x-axis discussion. When you mentioned adding x-axis adjustment, I thought you were only talking about matching the height to the tilt of the staff line, but I was not correct! If I'm understanding it correctly now, from what I'm observing when I click on "Match Height" the overlapping bounding boxes stop overlapping. I'm discovering that this creates two small problems:
- At the moment, bounding box placement is not ideal in the straight-outta-OMR file, so removing any overlap doesn't really make things better. 
- When two bounding boxes are almost completely overlapping, when the overlap is removed I'm sometimes left with a suuuuuper thin bounding box that's very difficult to locate and select.

I'm wondering if it would be ok to remove the x-axis adjustment from the `Match Height` function and instead implement it as the corrector is correcting. So overlap is removed only when a bounding box border has been manually moved by the user. Does that make sense?

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes.

**Comment by JoyfulGen** [comment]
@yinanazhou it works! Question: would an automatic adjustment of overlapping bboxes when a user changes one bbox be possible, or is it preferable not to have this kind of automatic action?

**Comment by yinanazhou** [comment]
@JoyfulGen I'm glad it works! 

We can provide an option that deals with overlaps. Could you describe when such an option could be helpful?

**Comment by JoyfulGen** [comment]
@yinanazhou my idea would be that overlaps are automatically corrected only when the corrector interacts with a bounding box. So if I resize a bbox, any other bbox overlapping with the first bbox _after_ resizing adjusts its width to remove the overlap. This means that as I go along the row, fixing one bbox border would actually be fixing two. Does that make sense?

**Comment by yinanazhou** [comment]
@JoyfulGen sorry somehow I missed this message! I understand your request, but I think that it'd be better to not automatically do anything as it may confuse new users.
