### ISSUE TITLE
[Verovio] Fetch Upstream with RISM

### ISSUE THREAD

**Issue by yinanazhou** [DDMAL/Neon2#1016]
This issue is for verovio merge with upstream. Due to the amount of conflicts, this is done by gradually merging DDMAL [branch](https://github.com/DDMAL/verovio/tree/develop-rism_merge) to RISM [branch](https://github.com/rism-digital/verovio/tree/develop-ddmal-merge).

Related issues:
https://github.com/DDMAL/Neon/issues/1007: move empty syl handling to Neon

Waiting Issues:
https://github.com/DDMAL/Neon/issues/995: support for different divLine types

**Comment by yinanazhou** [comment]
The merging verovio version can be tested via this [link](https://yinanazhou.github.io/Neon/). @JoyfulGen, could you please update action issues here? Thanks!

**Comment by JoyfulGen** [comment]
@yinanazhou everything looks good! I've corrected a folio with no issues so far.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I'm glad to hear that! Could you please let me know when it's ok to push changes to DDMAL Neon?

**Comment by JoyfulGen** [comment]
@yinanazhou, revisiting the folio has made me notice two bounding box bugs:

1. The same invisible bounding box problem as here: https://github.com/DDMAL/Neon/issues/1013
2. Another, trickier invisible bounding box problem. These are the steps:
- Open a fresh-outta-OMR file.
- Ungroup any long syllable ; the result is x number of syllables, the first having the original `syl` element and the others having no text. You can leave those empty or put text, the result will be the same.
- Save and refresh the page. The result is that the bounding boxes of the syllables that were created by the ungrouping are gone. This is different from issue number 1, because even if you enter text, the bounding boxes don't appear. Also, in the MEI, the `facs` number is very unusual and doesn't refer to any coordinates.

Here's an example of the MEI:

The syllable at the top is the first syllable of the ungrouping; it retained the `facs` of the original syllable, so it's fine. The syllables below (all called "wat" because I was feeling unimaginative) were created by the ungrouping. They all have the unusual `facs` that doesn't have coordinates and doesn't exist.

<img width="1016" alt="197r unusual syllables" src="https://github.com/DDMAL/Neon/assets/83373378/86ecc549-e6b4-4287-a26a-82c0d0bf52c9">


This is the complete MEI file I got that screenshot from: 
[197r(1).mei.zip](https://github.com/DDMAL/Neon/files/11662837/197r.1.mei.zip)

Other than those two bugs, everything works perfectly! When this is fixed, it'll be good to go.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, the invisible bounding box issue should already be fixed. Could you please confirm that it still happens [here](https://yinanazhou.github.io/Neon/)? If so, could you provide an example file for me to reproduce the issue? Thanks!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, the ungroup issue you mentioned should already be fixed. Could you please further test it? Thanks!

**Comment by JoyfulGen** [comment]
@yinanazhou both issues indeed are fixed! However, now every syllable in the "Syllables on this page" box has a little diamond next to it, even if it also has text. I can't click on the diamond separately from the text, and the diamond is there whether the syllable has text or not.

<img width="423" alt="Diamonds everywhere 200r" src="https://github.com/DDMAL/Neon/assets/83373378/e2d6887d-75e2-45db-b2af-37ea57a6b3c4">

This seems to be true both of files I had previously uploaded and a file I uploaded today.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've already pushed the changes for the issue you mentioned above.

**Comment by JoyfulGen** [comment]
@yinanazhou indeed you have! It all looks good now; all bounding boxes and text nuggets appear to be behaving as expected. I think you're good to go!

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I pushed some changes to verovio. Could you please check if everything works as expected [here](https://yinanazhou.github.io/Neon/) now? Thanks!

**Comment by JoyfulGen** [comment]
@yinanazhou it all looks good!

**Comment by yinanazhou** [comment]
The RISM - DDMAL merge has completed. The changes is already on `gh-pages`. Closing issue now.
