### ISSUE TITLE
Neume disappears when toggling ligature

### ISSUE THREAD

**Issue by PhoebeDM** [DDMAL/Neon2#1176]
When toggling a ligature and the two punctums are next to each other, moving the first punctum up to where it's supposed to be causes it to disappear and leave behind a little stem to the left. Anna said this might have happened before? 

<img width="79" alt="Screenshot 2024-01-10 at 8 15 51 PM" src="https://github.com/DDMAL/Neon/assets/113624849/def55f6d-2faa-4c81-a32d-e2abf17d9373">
<img width="95" alt="Screenshot 2024-01-10 at 8 15 39 PM" src="https://github.com/DDMAL/Neon/assets/113624849/a1113461-973c-4121-83b6-58d9401e9b7f">

**Comment by yinanazhou** [comment]
Could you please provide the files in this example? Thanks!

**Comment by annamorphism** [comment]
@yinanazhou I know @PhoebeDM is working with folio 145r from Einsiedeln; the offending neume depicted is on the eighth staff down (or so). 
I haven't yet succeeded in replicating exactly this (I am not sure how @PhoebeDM is getting the option to toggle ligature on two components on the same line), but I've gotten a similar disappearing neume that seems relevant:

Here is the staff in question (without all the extraneous stuff). I've added two neume components  (orange and pink) in between those already present in the first dark blue neume. 
<img width="689" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/fbd3efa7-7eea-40d1-ab9c-6bb7c5d3ed57">

When I try to group that orange neume component with the blue ones (so that I can turn it into a ligature later) I get this: 
<img width="654" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/c87fc8ef-8250-4f4d-972a-1c4fce8264d8">

Here's the MEI snippet from before: 
<img width="984" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/610f2762-1bba-4298-8363-affd832652da">


And here is after my grouping effort:
<img width="955" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/d23a4a3f-01eb-499b-82f9-be2be887e9e9">

It stands out to me that the first neume component of syllable "sl788jt" is apparently on a g and ligated=true, when it is to all appearances on an A and not attached to anything...

**Comment by annamorphism** [comment]
@JoyfulGen has pointed out this is actually due to https://github.com/DDMAL/Rodan/issues/1113 !

**Comment by annamorphism** [comment]
So it sounds like the _real_ solution is to have MEI-encoding properly encode ligatures so they don't lose their other halves, which is what causes the "chaos" described by @JoyfulGen .
However, given that such encoding problems apparently do exist and are treated as valid MEI, perhaps Neon could check for ligated=true attributes without a matching pair and flag/remove them (or else make it so that the ligated=true attribute doesn't produce this behaviour, but that sounds harder...)

**Comment by JoyfulGen** [comment]
@annamorphism there's already a notification system in place where Neon will warn you of any incomplete obliques! They also get listed in the error log, so the user can find them that way.

**Comment by annamorphism** [comment]
I thought it was something we had already! But then I thought it was maybe just a good idea we'd had and not implemented...

**Comment by yinanazhou** [comment]
Hi @JoyfulGen and @PhoebeDM, I've pushed the changes. I added a new MEI Action `Untoggle Invalid Obliques` to remove the "ligated" value. Please let me know if this still happens after the action.
