### ISSUE TITLE
If a syllable contains a divisio and an accidental, odd things happen

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1184]
If a syllable contains both a divisio and an accidental, selecting and ungrouping the syllable can cause odd behaviours. The order the neume, divisio, and accidental are in seem to influence the result. Here's what I've found:

- Order: neume - divisio - accidental
Result: At first nothing happens, but if you do any other action on the page the accidental disappears.
- Order: neume - accidental - divisio
Result: At first nothing happens, but if you do any other action on the page the _divisio_ disappears.
- Order: accidental - divisio - neume
Result: The accidental ungroups, but the divisio becomes its own syllable.
- Order: divisio - accidental - neume 
Result: The divisio ungroups, but the accidental becomes its own syllable

The last two are sometimes completely fine... I have no idea why.

Permutations where everything is always fine: 
divisio - neume - accidental
accidental - neume - divisio

**Comment by annamorphism** [comment]
this is super intriguing! Do accidentals you add and uploaded accidentals behave the same way? (I'm thinking of the problem back in #824)

**Comment by JoyfulGen** [comment]
> this is super intriguing! Do accidentals you add and uploaded accidentals behave the same way? (I'm thinking of the problem back in #824)

@annamorphism as far as I've been able to tell, yes!

**Comment by annamorphism** [comment]
I can confirm the first two of @JoyfulGen's results! I haven't started in on the other two, because I can across another possibly related issue while testing:
Sometimes, in trying to ungroup these weird little syllables, the ungroup success doesn't show up right away. If, in your impatience and/or confusion, you hit ungroup _again_, new weirdness happens: The MEI is still valid, neumes can still be manipulated normally, but you can't insert anything! Or at least, nothing shows up as being inserted--I think the MEI does, in fact, get the insertion memo. Further investigation to come.

**Comment by annamorphism** [comment]
...or, apparently, Neon will sometimes tell you the result is invalid MEI and will (as punishment) drag the neumes in a very off-kilter way instead of putting them where they should be. It also acts weird about modifying the file: for this set of neumes, the downloaded MEI says they are all on C.  (in fact the MEI is as far as I can tell identical to the "valid" file I got when insertion wasn't happening, so maybe there is some sort of lag between the file change and my downloaded version, or the valid/invalid check and my download).
<img width="527" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/eb0642d7-3b30-4934-9460-88efd1fc8e58">

<img width="515" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/9b93b553-ebf0-48d2-b741-f67225389cd9">

**Comment by annamorphism** [comment]
Part of the "the last ones are sometimes fine" seems to be where things are. By moving things juuuuuust slightly left or right, I can change whether the accidental is its own syllable or not.

**Comment by annamorphism** [comment]
<img width="179" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/acf3658c-4a73-4ba1-9008-a78b9cd3e901">
ungroups to 
<img width="175" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/715d4621-beb2-4d11-8b08-f18b8481d1a3">
but this 
<img width="237" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/8b93864f-1839-492c-a4b5-b96587dea2f5">

ungroups to 
<img width="165" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/f4d422d0-c385-41d2-8fda-ac6525a23524">
The difference is that the accidental's zone starts about 12 pixels to the left in the orange version, which means it is before, rather than after, where the first neume starts. (This neume is named "zalfbug" which seems somehow a propos).
<img width="1032" alt="image" src="https://github.com/DDMAL/Neon/assets/67451875/41cbbe6e-8f8c-4b12-bb2b-23acc0efe80e">

**Comment by yinanazhou** [comment]
Hi @JoyfulGen I've pushed the changes. Please let me know if this is still happening :)

**Comment by JoyfulGen** [comment]
@yinanazhou I think it's still happening! Now though after ungrouping the syllable, other actions on the page stop working completely.

**Comment by yinanazhou** [comment]
Hi @JoyfulGen can you provide more details? I cannot reproduce it on my end.

**Comment by JoyfulGen** [comment]
@yinanazhou certainly! I'm creating a syllable that goes neume-divisio-accidental and then selecting it to ungroup it. When I click "ungroup" nothing happens. If I then try to move another element on the page, it moves erratically and doesn't snap to the nearest pitch when I let go. I also can't delete anything. Here's a demo:

https://github.com/DDMAL/Neon/assets/83373378/fe64cfbd-6612-4379-9ba4-fb6394a933aa

**Comment by yinanazhou** [comment]
Hi @JoyfulGen, I've pushed the changes.

**Comment by JoyfulGen** [comment]
@yinanazhou it all works now! Thank you :)
