### ISSUE TITLE
tutorial video links don't work?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon2#1233]
I was going to point somebody to the tutorials today, only to get this when I click on the lovely links 
![image](https://github.com/DDMAL/Neon/assets/67451875/be84bac3-e40f-4be0-8ddf-d05d466388f5)

What's going on?

I also can't get any sample files to load (see below), which is a separate problem but also makes it hard to demo....

![image](https://github.com/DDMAL/Neon/assets/67451875/b9131402-2cd2-47d5-9f91-348ddda273f9)

**Comment by yinanazhou** [comment]
For sample files, could you try to force reload the file system? Notes that this will delete all the local files, including the ones you have uploaded before.

1. Right click in the nav bar, and select `inspect`
2. Go to `Application` tab
3. In `Storage`, click on `Local storage`, right click on `https://yinanazhou.github.io`, and `Clear`
4. In `Storage`, click on `IndexedDB`, for each item in this menu, click on it, and then in the right panel, click `Delete database`
5. Refresh page

Please let me know if this helps.

**Comment by JoyfulGen** [comment]
@annamorphism WHAT. I'm so sorry!!! I'm going to assume I did something weird with github, because if I just copy and paste the links they work just fine. I'll try to clean it up, but in the meantime here are the tutorials:
Part 1: https://www.youtube.com/watch?v=3IrCnsg35rs&ab_channel=Genevi%C3%A8veGates-Panneton
Part 2: https://www.youtube.com/watch?v=Tuj8IEknHDs&ab_channel=Genevi%C3%A8veGates-Panneton
Part 3: https://www.youtube.com/watch?v=8E7j9fhbZcA&ab_channel=Genevi%C3%A8veGates-Panneton
Part 4: https://www.youtube.com/watch?v=6FF4uppY7Ho&ab_channel=Genevi%C3%A8veGates-Panneton
Part 5: https://www.youtube.com/watch?v=prgrYRdf2rI&ab_channel=Genevi%C3%A8veGates-Panneton

I hope those work!

**Comment by JoyfulGen** [comment]
Update: I think I've corrected the links in the wiki. @annamorphism does it work now?

**Comment by annamorphism** [comment]
Ok this seems to be fixed!
