### ISSUE TITLE
Icon sometimes disappears

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#172]
The icon for the dropdown's in the extra editing tools sometimes stops rendering. This is probably an import issue and needs to be fixed.

**Comment by zoemcl** [comment]
This seems to be an even bigger issue. All images (svg/png) seem to disappear sometimes.

**Comment by JRegimbal** [comment]
We need someone to report what status they get when trying to load the images when they fail.

**Comment by JRegimbal** [comment]
In Rodan this seems to be because of an issue in the wrapper that has since been fixed (wrong action done on autosave). That threw a 401 error. For the standalone it just takes the server a long time to respond and there is very little consistency. This may just be the server failing to respond properly rather than an actual issue in the Neon code.
