### ISSUE TITLE
Dragging ligature issues

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#187]
Dragging ligatures often causes the two neume components to split in two and they become very hard to work with.

**Comment by JRegimbal** [comment]
This is largely because the two neume components have the same zone. I think it'll be fixed if we get MEIs with separate zones for each, even if that zone is (at least initially) the same. If the goal is for the entire ligature to move, then we may need a better way to deal with that than selecting the ligature and the little line at the side.

**Comment by zoemcl** [comment]
refer to #190
