### ISSUE TITLE
Neume information

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#23]
provide neume information (system position, pitch, etc.) when clicked on.

**Comment by ATranimal** [comment]
50fca0e52fcfb1c9ea1c8ab5f6c0e5fe3d6b42f5

Preliminary work completed, information box now pops up and displays pitch information for neumes + custos.

TODO:
-Refactor into its own js file
-Somehow get clef information (ID is missing since its not a separate XML element)
-Get grouping name from verovio (hard? since its a map)

**Comment by zoemcl** [comment]
Only thing left to do would be to display the retrieved information in a nice and consistent way but that is purely a cosmetic issue.

**Comment by JRegimbal** [comment]
Tried to make it look more like the info box in Neon.js in 0ead422.

**Comment by zoemcl** [comment]
Looks good!
