### ISSUE TITLE
boundaryEnd error (Neon3)

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#25]
Depending on the version of the verovio toolkit, the following error is thrown when saving and reloading an MEI file:

verovio-toolkit.js:1 --> [Error] Could not find start element '' for boundaryEnd

This causes the system to be truncated and several neumes are not rendered properly.

**Comment by JRegimbal** [comment]
Can't replicate the boundaryEnd issue using a verovio toolkit build on [this commit](https://github.com/DDMAL/verovio/commit/070042188efb8f40bc10925824e2958de18bfb21).

However the truncation is still occurring because a `</layer>` is inserted after the first neume. I'm closing this issue for now but will make a new one specifically about the misplaced `</layer>` tag.

**Comment by JRegimbal** [comment]
I may have spoke too soon. Looks like boundaryEnd is still an issue (although less frequent). The truncation is due to the `</layer>`. Since I don't know if these are related or just two editor-related issues, the `</layer>` issue is #35.
