### ISSUE TITLE
Find a way to resize or split staves

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#278]
Currently there is no way resize or split staves. Sometimes, two staves can be read as one and the only way to correct this error is to delete the entire staff (and elements), insert the two staves, and reinsert all the elements. This can be quite a long process so there should be a way to make it faster, either by splitting ore resizing.

**Comment by JRegimbal** [comment]
I think we need to support resizing *and* splitting staves. If we only support resizing, then the elements we want to put on the newly inserting staff will still be on the old resized staff. If we only support splitting, we'd need to essentially have the backend for resizing anyway since one staff will remain the same and just include a different bounding box and at most as many children.

Splitting seems to me to be the priority since a frontend for resizing might take a lot of work.
