### ISSUE TITLE
Organize d3 vs jquery 

### ISSUE THREAD

**Issue by zoemcl** [DDMAL/Neon2#81]
Right now there is no clear division as when to use jquery and when to use d3 in the project. We should find a way to distinctly organize this and refactor the code.

**Comment by JRegimbal** [comment]
@zoemcl
Tried to use Jquery for all listeners other than drag, since d3 makes that easier. But there might be no point in even keeping d3 since we can implement those listeners in jquery or plain js and other than listeners we only use d3 for getting/setting attributes from what I can see. More on this in the slack.

See [this branch](https://github.com/DDMAL/Neon2/tree/refactor/d3-jquery).

**Comment by JRegimbal** [comment]
Resolved by #90.
